name: C++ CI

on:
  push:
    branches: [second]
  pull_request:
    branches: [second]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build
        run: make tests

      - name: Run tests
        run: ./test-player